# Build stage
FROM golang:1.16-alpine AS builder

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o server .

# Final stage
FROM scratch

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/server .

EXPOSE 8080

USER 1001

CMD ["./server"]
