# Use the official Go 1.16 image as the base
FROM golang:1.16

# Install Git
RUN apt-get update && apt-get install -y git

# Set the working directory
WORKDIR /go/src/app

# Clone the repository
RUN git clone https://github.com/docker-hy/material-applications.git .

# Set the REQUEST_ORIGIN environment variable
ENV REQUEST_ORIGIN=http://localhost

# Build the backend server application
RUN go build -o server ./example-backend

# Expose port 8080 for the application
EXPOSE 8080

# Set the command to run the server
CMD ["sh", "-c", "cd /go/material-applications/example-backend/ && ./server"]

